name: test-workflow-activity
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  #Trigger a specific brach:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v



